"""metering record per account

Revision ID: 9577aff2f1f6
Revises: 3b44ef1c41a0
Create Date: 2023-10-02 09:29:13.062663+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9577aff2f1f6"
down_revision: Union[str, None] = "3b44ef1c41a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metering", sa.Column("cloud", sa.String(length=10), nullable=True))
    op.add_column("metering", sa.Column("account_id", sa.String(length=36), nullable=True))
    op.add_column("metering", sa.Column("account_name", sa.String(length=255), nullable=True))
    # safe to drop column here, since we are still in alpha
    op.drop_column("metering", "nr_of_accounts_collected", if_exists=True)
    # ### end Alembic commands ###
