"""add compute to json_store

Revision ID: 2cbb6dcf9d01
Revises: 337d9a21e53c
Create Date: 2023-10-18 10:10:08.859003+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cbb6dcf9d01"
down_revision: Union[str, None] = "337d9a21e53c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("key_value_json", sa.Column("version_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###
