"""add cloud account

Revision ID: 9f0f5d8ec3d5
Revises: b768e81c0d5c
Create Date: 2023-09-27 15:27:39.397364+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy import GUID

# revision identifiers, used by Alembic.
revision: str = "9f0f5d8ec3d5"
down_revision: Union[str, None] = "b768e81c0d5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_account",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("tenant_id", GUID(), nullable=False),
        sa.Column("cloud", sa.String(length=12), nullable=False),
        sa.Column("account_id", sa.String(length=12), nullable=False),
        sa.Column("aws_role_name", sa.String(length=64), nullable=False),
        sa.Column("aws_external_id", GUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["organization.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "account_id"),
    )
    op.create_index(op.f("ix_cloud_account_tenant_id"), "cloud_account", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
