"""graph database access

Revision ID: 995b51027ef6
Revises: a1d4ec210f18
Create Date: 2023-09-25 10:53:08.032138+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "995b51027ef6"
down_revision: Union[str, None] = "a1d4ec210f18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_database_access",
        sa.Column("tenant_id", GUID, nullable=False),
        sa.Column("server", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=36), nullable=False),
        sa.Column("password", sa.String(length=20), nullable=False),
        sa.Column("database", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("graph_database_access")
    # ### end Alembic commands ###
    pass
