"""cloud account names and aliases

Revision ID: 307acabf02b6
Revises: e5a452318fa7
Create Date: 2023-11-07 16:47:14.722872+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "307acabf02b6"
down_revision: Union[str, None] = "e5a452318fa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cloud_account", sa.Column("aws_can_discover_names", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column("cloud_account", sa.Column("user_account_name", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("api_account_name", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("api_account_alias", sa.String(length=64), nullable=True))
    op.alter_column("cloud_account", "aws_role_name", existing_type=mysql.VARCHAR(length=64), nullable=True)
    op.drop_column("cloud_account", "name")
    # ### end Alembic commands ###
