"""add name to cloud account repo

Revision ID: 69f29fc94a5c
Revises: 4df8ea080f3e
Create Date: 2023-10-20 13:03:37.370998+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69f29fc94a5c"
down_revision: Union[str, None] = "4df8ea080f3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("name", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
