"""add the next_tenant_run table

Revision ID: cd9ef4e05fdd
Revises: 9b482c179740
Create Date: 2023-10-13 11:23:36.653345+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID
from fixbackend.sqlalechemy_extensions import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "cd9ef4e05fdd"
down_revision: Union[str, None] = "9b482c179740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "next_tenant_run",
        sa.Column("tenant_id", GUID, nullable=False),
        sa.Column("at", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_index(op.f("ix_next_tenant_run_at"), "next_tenant_run", ["at"], unique=False)
    # ### end Alembic commands ###
