"""add configured flag to cloud account

Revision ID: e5a452318fa7
Revises: d9be24f944dc
Create Date: 2023-10-27 12:46:40.781041+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5a452318fa7"
down_revision: Union[str, None] = "d9be24f944dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("is_configured", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("cloud_account", sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###
