"""add organization models

Revision ID: 9bd6d9dc6957
Revises: 5eaf979cfb28
Create Date: 2023-08-31 14:38:18.402653+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '9bd6d9dc6957'
down_revision: Union[str, None] = '5eaf979cfb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', GUID, nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organization_invite',
    sa.Column('id', GUID, nullable=False),
    sa.Column('organization_id', GUID, nullable=False),
    sa.Column('user_id', GUID, nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('organization_id', GUID, nullable=False),
    sa.Column('user_id', GUID, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('organization_owners',
    sa.Column('organization_id', GUID, nullable=False),
    sa.Column('user_id', GUID, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_owners')
    op.drop_table('organization_members')
    op.drop_table('organization_invite')
    op.drop_table('organization')
    # ### end Alembic commands ###
