"""cloud account state machine

Revision ID: 886ab1ab881e
Revises: e5a452318fa7
Create Date: 2023-11-08 16:10:12.694233+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "886ab1ab881e"
down_revision: Union[str, None] = "e5a452318fa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("privileged", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("cloud_account", sa.Column("user_account_name", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("api_account_name", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("api_account_alias", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("state", sa.String(length=64), nullable=True))
    op.add_column("cloud_account", sa.Column("error", sa.String(length=64), nullable=True))
    op.alter_column("cloud_account", "aws_external_id", existing_type=mysql.CHAR(length=36), nullable=True)
    op.alter_column("cloud_account", "aws_role_name", existing_type=mysql.VARCHAR(length=64), nullable=True)
    op.drop_column("cloud_account", "name")

    # ### end Alembic commands ###
