"""add biling address table

Revision ID: 661679cf9747
Revises: 917c74178e81
Create Date: 2023-12-15 11:04:08.180190+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = "661679cf9747"
down_revision: Union[str, None] = "917c74178e81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_address",
        sa.Column("user_id", GUID, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("company", sa.String(length=256), nullable=True),
        sa.Column("address_line_1", sa.String(length=256), nullable=False),
        sa.Column("address_line_2", sa.String(length=256), nullable=False),
        sa.Column("postal_code", sa.String(length=256), nullable=False),
        sa.Column("city", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=256), nullable=False),
        sa.Column("country", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###
