"""merge last_scan table to cloud account

Revision ID: b33942763df4
Revises: 886ab1ab881e
Create Date: 2023-11-16 16:57:50.123194+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from fixbackend.sqlalechemy_extensions import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "b33942763df4"
down_revision: Union[str, None] = "886ab1ab881e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("last_scan_reposotory")
    op.add_column("cloud_account", sa.Column("next_scan", UTCDateTime(timezone=True), nullable=True))
    op.add_column(
        "cloud_account", sa.Column("last_scan_duration_seconds", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("cloud_account", sa.Column("last_scan_started_at", UTCDateTime(timezone=True), nullable=True))
    op.add_column(
        "cloud_account", sa.Column("last_scan_resources_scanned", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###
