"""support invitation by email

Revision ID: a3024445ff9c
Revises: d294f6e4b5dc
Create Date: 2023-12-06 11:02:53.960375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a3024445ff9c"
down_revision: Union[str, None] = "d294f6e4b5dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_invite", sa.Column("user_email", sa.String(length=320), nullable=False, server_default="")
    )
    op.alter_column("organization_invite", "user_id", existing_type=mysql.CHAR(length=36), nullable=True)
    # ### end Alembic commands ###
