"""add created_at/updated_at to cloud_account

Revision ID: 1ccf5fc88e67
Revises: d294f6e4b5dc
Create Date: 2023-12-07 12:14:35.061355+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1ccf5fc88e67"
down_revision: Union[str, None] = "d294f6e4b5dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # user_email is not nullable, so we need to drop all existing invites
    op.execute("TRUNCATE TABLE organization_invite")

    op.add_column("organization_invite", sa.Column("user_email", sa.String(length=320), nullable=False))
    op.add_column("organization_invite", sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "organization_invite", sa.Column("version_id", sa.Integer(), nullable=False, server_default=sa.text("0"))
    )
    op.create_unique_constraint(None, "organization_invite", ["user_email"])
    op.drop_constraint("organization_invite_ibfk_2", "organization_invite", type_="foreignkey")
    op.drop_column("organization_invite", "user_id")
    # ### end Alembic commands ###
