"""add security tier to workspace

Revision ID: 2354e2e14300
Revises: 1ccf5fc88e67
Create Date: 2023-12-11 12:17:42.072422+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2354e2e14300"
down_revision: Union[str, None] = "1ccf5fc88e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metering", sa.Column("security_tier", sa.String(length=64), nullable=False, server_default="FreeAccount")
    )
    op.add_column(
        "organization", sa.Column("security_tier", sa.String(length=64), nullable=False, server_default="FreeAccount")
    )
    # ### end Alembic commands ###
