"""indexes for workspace tier

Revision ID: afe34c8861f5
Revises: 992c435d91ef
Create Date: 2024-04-03 13:18:52.751618+00:00

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "afe34c8861f5"
down_revision: Union[str, None] = "992c435d91ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_organization_created_at"), "organization", ["created_at"], unique=False)
    op.create_index(op.f("ix_organization_tier"), "organization", ["tier"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### end Alembic commands ###
    pass
