"""add subscription id to workspace

Revision ID: dfb8543513a5
Revises: 625f5b0ac493
Create Date: 2024-02-29 15:53:08.220955+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "dfb8543513a5"
down_revision: Union[str, None] = "625f5b0ac493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("subscription_id", GUID, nullable=True))
    op.create_index(op.f("ix_organization_subscription_id"), "organization", ["subscription_id"], unique=False)
    op.drop_index("ix_subscriptions_workspace_id", table_name="subscriptions")
    op.drop_column("subscriptions", "workspace_id")
    # ### end Alembic commands ###
