"""add created/updated times to workspace

Revision ID: 37c97e80bf4f
Revises: bd81f26e562a
Create Date: 2024-03-21 15:03:31.826734+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fixbackend.sqlalechemy_extensions import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = "37c97e80bf4f"
down_revision: Union[str, None] = "bd81f26e562a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization",
        sa.Column("created_at", UTCDateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "organization",
        sa.Column("updated_at", UTCDateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "updated_at")
    op.drop_column("organization", "created_at")
    # ### end Alembic commands ###
