"""add a workspace_id index to role repo

Revision ID: 6a28d961d926
Revises: f4b1a5c0d236
Create Date: 2024-02-15 16:55:07.020099+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a28d961d926"
down_revision: Union[str, None] = "f4b1a5c0d236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_role_assignment_workspace_id"), "user_role_assignment", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###
