"""insert trial end notification emails

Revision ID: a75f4b3d34cf
Revises: 51b7e006cee5
Create Date: 2024-04-05 13:42:35.072377+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a75f4b3d34cf"
down_revision: Union[str, None] = "51b7e006cee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    field_not_used_here = 42

    op.execute( f"INSERT INTO scheduled_email (id, kind, after) VALUES ('829c95f1-28e3-4c2c-af04-a30fc715bcb1', 'trial_expired', {field_not_used_here})" )  # fmt: skip # noqa
    op.execute( f"INSERT INTO scheduled_email (id, kind, after) VALUES ('829c95f1-28e3-4c2c-af04-a30fc715bcb2', 'trial_expires', {field_not_used_here})" )  # fmt: skip # noqa
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
