"""add aws tier preference table

Revision ID: ec534aae73ac
Revises: f510b2e977db
Create Date: 2024-05-27 14:53:15.502420+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID
from fixbackend.sqlalechemy_extensions import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "ec534aae73ac"
down_revision: Union[str, None] = "f510b2e977db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aws_tier_preferences",
        sa.Column("workspace_id", GUID, nullable=False),
        sa.Column("desired_product_tier", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
