"""add username to oauth account

Revision ID: f4b1a5c0d236
Revises: aae08c771e83
Create Date: 2024-02-13 19:11:03.506008+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4b1a5c0d236"
down_revision: Union[str, None] = "aae08c771e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_account", sa.Column("username", sa.String(length=320), nullable=True))
    # ### end Alembic commands ###
