"""store azure data in cloud account repo info

Revision ID: 167047784340
Revises: 9cd3c7b42670
Create Date: 2024-06-10 15:48:38.834945+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "167047784340"
down_revision: Union[str, None] = "9cd3c7b42670"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("azure_credential_id", GUID, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cloud_account", "azure_credential_id")
    # ### end Alembic commands ###
