"""add index on workspace slug

Revision ID: 8907ec70cc77
Revises: 51b7e006cee5
Create Date: 2024-04-10 11:28:30.055276+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8907ec70cc77"
down_revision: Union[str, None] = "51b7e006cee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("slug", table_name="organization")
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
