"""user notification table

Revision ID: 76394309daea
Revises: 84cfaaf4b05a
Create Date: 2024-02-02 12:15:39.819970+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "76394309daea"
down_revision: Union[str, None] = "84cfaaf4b05a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notification_settings",
        sa.Column("user_id", GUID, nullable=False),
        sa.Column("weekly_report", sa.Boolean(), nullable=False),
        sa.Column("inactivity_reminder", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
