"""add failed collect count

Revision ID: f00a78f4ef30
Revises: dfb8543513a5
Create Date: 2024-03-05 09:26:41.322936+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f00a78f4ef30"
down_revision: Union[str, None] = "dfb8543513a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("failed_scan_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###
