"""add one time emails table

Revision ID: 9e047608dacc
Revises: 8907ec70cc77
Create Date: 2024-04-16 17:18:40.217272+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID
from fixbackend.sqlalechemy_extensions import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "9e047608dacc"
down_revision: Union[str, None] = "8907ec70cc77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fire_and_forget_email",
        sa.Column("id", GUID, nullable=False),
        sa.Column("kind", sa.String(length=256), nullable=False),
        sa.Column("user_id", GUID, nullable=True),
        sa.Column("workspace_id", GUID, nullable=True),
        sa.Column("subject", sa.String(length=1024), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("html_content", sa.Text(), nullable=True),
        sa.Column("scheduled_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("sent_at", UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fire_and_forget_email_scheduled_at"), "fire_and_forget_email", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_fire_and_forget_email_sent_at"), "fire_and_forget_email", ["sent_at"], unique=False)
    op.create_index(op.f("ix_fire_and_forget_email_user_id"), "fire_and_forget_email", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_fire_and_forget_email_workspace_id"), "fire_and_forget_email", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
