"""roles repository

Revision ID: db8c4a60218d
Revises: 76394309daea
Create Date: 2024-02-07 19:35:01.423878+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "db8c4a60218d"
down_revision: Union[str, None] = "76394309daea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_role_assignment",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("role_name", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_name"),
    )
    op.create_index(op.f("ix_user_role_assignment_user_id"), "user_role_assignment", ["user_id"], unique=False)

    op.execute(
        """
        INSERT INTO user_role_assignment (id, user_id, role_name)
        SELECT uuid(), id, 'workspace_admin'
        FROM user
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_assignment_user_id"), table_name="user_role_assignment")
    op.drop_table("user_role_assignment")
    # ### end Alembic commands ###
