"""roles repository

Revision ID: aae08c771e83
Revises: 76394309daea
Create Date: 2024-02-08 14:44:47.321715+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = "aae08c771e83"
down_revision: Union[str, None] = "76394309daea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_role_assignment",
        sa.Column("id", GUID, nullable=False),
        sa.Column("user_id", GUID, nullable=False),
        sa.Column("workspace_id", GUID, nullable=False),
        sa.Column("role_names", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "workspace_id"),
    )
    op.create_index(op.f("ix_user_role_assignment_user_id"), "user_role_assignment", ["user_id"], unique=False)

    workspace_owner = str(2**2)

    op.execute(
        f"""
        INSERT INTO user_role_assignment (id, user_id, workspace_id, role_names)
        SELECT uuid(), user_id, organization_id, '{workspace_owner}'
        FROM organization_owners
        """
    )

    workspace_member = str(2**0)

    op.execute(
        f"""
        INSERT INTO user_role_assignment (id, user_id, workspace_id, role_names)
        SELECT uuid(), user_id, organization_id, '{workspace_member}'
        FROM organization_members
        """
    )
    # ### end Alembic commands ###
