"""store cf stack version in cloud account

Revision ID: 894e2b7af974
Revises: 6a28d961d926
Create Date: 2024-02-21 13:05:45.488098+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "894e2b7af974"
down_revision: Union[str, None] = "6a28d961d926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_account", sa.Column("cf_stack_version", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###
