version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: "fixbackend-app-${USER}"

    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.ssh:/home/vscode/.ssh

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: "fixbackend-redis-${USER}"

  db:
    image: mariadb:11
    ports:
      - "3306:3306"
    restart: unless-stopped
    container_name: "fixbackend-mariadb-${USER}"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data:
